# Generated by Django 4.2.1 on 2023-12-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='None', max_length=50)),
                ('intra_username', models.CharField(default='None', max_length=50, unique=True)),
                ('email', models.EmailField(default='None', max_length=100)),
                ('image_link', models.CharField(default='None', max_length=150)),
                ('current_status', models.CharField(default='Offline', max_length=10)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='default_value', max_length=100)),
                ('nickname', models.CharField(default='default_value', max_length=100)),
                ('email', models.EmailField(default='default_value', max_length=100)),
                ('image_link', models.CharField(default='default_value', max_length=150)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('win', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('loser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='myapp.user')),
                ('winner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'match')},
            },
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_of', to='myapp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
