# Generated by Django 4.2.1 on 2024-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
    ]
