# Generated by Django 4.2.1 on 2023-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='password',
        ),
        migrations.AddField(
            model_name='user_data',
            name='image_link',
            field=models.CharField(default='default_value', max_length=150),
        ),
        migrations.AddField(
            model_name='user_data',
            name='login',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='user_data',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_data',
            name='nickname',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='user_data',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
