# Generated by Django 4.2.1 on 2024-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='last_login',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
    ]
