# Generated by Django 4.2.1 on 2024-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_profile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
