# Generated by Django 4.2.1 on 2024-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_profile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
