# Generated by Django 4.2.1 on 2024-02-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_profile_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='two_factor_auth_status',
        ),
    ]
